// Generated by nuxi
/// <reference types="@nuxt/content" />
/// <reference types="@pinia/nuxt" />
/// <reference types="@pinia-plugin-persistedstate/nuxt" />
/// <reference types="@unocss/nuxt" />
/// <reference types="@vueuse/nuxt" />
/// <reference types="@nuxtjs/color-mode" />
/// <reference types="@nuxt/devtools" />
/// <reference types="@vite-pwa/nuxt" />
/// <reference types="nuxt-vitest" />
/// <reference types="@nuxt/telemetry" />
/// <reference types="nuxt" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/app.config.d.ts" />
/// <reference path="types/content.d.ts" />
/// <reference types="@pinia/nuxt" />
/// <reference types="vite-plugin-pwa/client" />
/// <reference types="vite-plugin-pwa/info" />
/// <reference types="vue-router" />
/// <reference path="types/middleware.d.ts" />
/// <reference path="types/layouts.d.ts" />
/// <reference path="components.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="imports.d.ts" />
/// <reference path="types/nitro.d.ts" />

export {}
